####
POST http://127.0.0.1:8080/register

Content-Type: application/json

{}


####
POST http://127.0.0.1:8080/create-energy-usage
Content-Type: application/json

{
  "user_uuid": "9b7fbcb9-0efa-417a-9587-5ef87bdebcd0",
  "average_monthly_bill": 1800,
  "average_natural_gas_bill": 580,
  "monthly_fuel_bill": 75
}
###
POST http://127.0.0.1:8080/create-waste-sector
Content-Type: application/json

{
  "user_uuid": "9b7fbcb9-0efa-417a-9587-5ef87bdebcd0",
  "waste_kg": 5070,
  "recycled_or_composted_kg": 300
}

###
POST http://127.0.0.1:8080/create-business-travel
Content-Type: application/json

{
  "user_uuid": "9b7fbcb9-0efa-417a-9587-5ef87bdebcd0",
  "kilometers_per_year": 70000,
  "average_efficiency_per_100km": 8.5
}

###

### Get calculated energy usage carbon footprint
GET http://localhost:8080/get-energy-usage?user_uuid=9b7fbcb9-0efa-417a-9587-5ef87bdebcd0
Accept: application/json

###

### Get calculated waste sector carbon footprint
GET http://localhost:8080/get-business-travel?user_uuid=9b7fbcb9-0efa-417a-9587-5ef87bdebcd0
Accept: application/json

###

### Get calculated business travel carbon footprint
GET http://localhost:8080/get-waste-sector?user_uuid=9b7fbcb9-0efa-417a-9587-5ef87bdebcd0
Accept: application/json
###
### Get c
GET http://localhost:8080/give-recommendation?user_uuid=7d6a7117-cb4c-420e-b8b8-525c1838b79d
Accept: application/json

