#### Register a new report
POST http://127.0.0.1:8080/register
Content-Type: application/json

{}

#### Create energy usage data
POST http://127.0.0.1:8080/create-energy-usage
Content-Type: application/json

{
  "report_uuid": "f2ecde5b-5019-450c-b81a-3cde7937759a",
  "average_monthly_bill": 1800,
  "average_natural_gas_bill": 580,
  "monthly_fuel_bill": 75,
"city": "Berlin",
"company_name": "BMW"
}


#### Get calculated energy usage carbon footprint
POST http://localhost:8080/get-energy-usage?company_name=BMW
Accept: application/json

{
}
